#!/usr/bin/env bash
filter='shit'

if git diff --cached | grep -i "$filter"; then  # looking for "shit" in repository changes
	if git diff --cached | grep -i "$filter" | grep -iq '+'; then  # check if "shit" was actually added, in case that it was already in file and is being removed
  		echo Please don\'t put that "$filter" into repository 1>&2
  		exit 1
	else echo Thank you for deleting all that "$filter"
		exit 0
	fi
fi
